### ISSUE TITLE
Review App Creation - Error in Running Scripts and Scaling Dynos step

### ISSUE THREAD

**Issue by abychat** [heroku/salesforce-buildpack#21]
I have been trying to use the sample app @ https://github.com/wadewegner/salesforce-dx-pipeline-sample and receive errors at the 'Run Scripts and scale dynos' step of the review app creation. The build and deployment goes well but the app isn't accessible because of the error.

I have updated my Heroku and Salesforce CLIs as well.

My forked repo with the updated setup.sh and related files is @ https://github.com/abychat/salesforce-dx-pipeline-sample

I tried this on another app and got the same result.

![image](https://user-images.githubusercontent.com/7586106/38439308-003f93ea-3992-11e8-8c95-7259fc71fdb3.png)

**Comment by jwsources** [comment]
Is something fails in the Run scripts section review the Release.log which you can find in the App itself not on the pipeline. Open the App and then look at the Activities tab. This might tell you why it failed, presumable your package fails to deploy. Can you deploy packages locally?

**Comment by wadewegner** [comment]
We had a poor config setting in the `app.json` while back. Have you tried this recently? I suspect we fixed this. I'm going to close. If you still have the problem, please re-open with details. Thanks!
