### ISSUE TITLE
Package installation requires respond to prompt and fails

### ISSUE THREAD

**Issue by jwsources** [heroku/salesforce-buildpack#23]
My package installation fails since it needed access to remote sites granted which it prompts for. I updated the code and created a pull request for adding --noprompt to the package installation command.

**Comment by douglascayers** [comment]
I think this has been resolved by https://github.com/heroku/salesforce-buildpack/pull/25

**Comment by wadewegner** [comment]
Yes. @jwsources if this is still a problem, please re-open.
