### ISSUE TITLE
Support running apex tests without Heroku CI

### ISSUE THREAD

**Issue by douglascayers** [heroku/salesforce-buildpack#33]
I propose that the `run-apex-tests` property parsed from `sfdx.yml` indicate whether the release phase explicitly runs apex tests or not rather than relying on Heroku CI enabled.

Currently, to get tests to run, then users must enable Heroku CI. However, Heroku CI is a paid add-on and creates its own scratch org separate from the scratch org used by Review Apps.

This feature change would cause the release script to explicitly run the apex tests after deploying code (package.xml or packages).

Benefit is that developers can get their builds to run their tests without paying for the Heroku CI add-on, but have the option to enable Heroku CI for its additional features of (a) GitHub Statuses and (b) control gate on automatic deployments and (c) testing for every push.

The biggest win here would be with Review Apps, and possible this feature might be scoped to Review stage entirely and leave Heroku CI for all other forms of test running.

**Comment by wadewegner** [comment]
@devarispbrown and @ike-delorenzo I'd like to get your input this feature request. Currently, we delegate the running of tests to Heroku CI. It's technically possible for us to include this as part of release phase, though. Do you agree there's value in this option and that Heroku CI is only needed for the value listed by @douglascayers?

**Comment by douglascayers** [comment]
Resolved per https://github.com/heroku/salesforce-buildpack/pull/38
