### ISSUE TITLE
Push rejected, failed to compile salesforce-buildpack app.

### ISSUE THREAD

**Issue by jlondrejcka** [heroku/salesforce-buildpack#40]
Howdy team, 

I am writing a blog post so ISVs can better adopt the buildpack, but just ran into an issue:

When I merge a pull request I am getting the following error:

`DEBUG] CMD: sfdx force:package2:list --json | jq '.result[] | select((.Name) == "mypipelinedemo")' | jq -r .Id
 ▸    force:package2:list is not a sfdx command.
 ▸    Perhaps you meant force:package:list
 ▸    Run sfdx help force for a list of available topics.
 !     Push rejected, failed to compile salesforce-buildpack app.
 !     Push failed`

Shouldn't the command be:  force:package:list, not force:package2:list?

**Comment by jlondrejcka** [comment]
@wadewegner following up on this, thanks!

**Comment by wadewegner** [comment]
Oh boy. For some reason, I don't recall seeing this notification. Sorry!

It looks like we need to update the commands. Sorry, I'll look into it.

**Comment by douglascayers** [comment]
Thanks for merging https://github.com/heroku/salesforce-buildpack/pull/38, @WadeWegner

That should resolve this issue
